/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forme;

import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import model.Poruka;
import model.User;
import niti.Nit;
import transfer.KlijentskiZahtev;

/**
 *
 * @author milos
 */
public class KlijentskaForma extends javax.swing.JFrame {

    private User trenutni;
    private Nit nit;
    /**
     * Creates new form KlijentskaForma
     */
    public KlijentskaForma() {
        initComponents();
        nit=new Nit(this);
        nit.start();
        jTextFieldPoslednjaPoruka.setEnabled(false);
    }

    public User getTrenutni() {
        return trenutni;
    }

    public void setTrenutni(User trenutni) {
        this.trenutni = trenutni;
    }

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonLogout = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableUseri = new javax.swing.JTable();
        jTextFieldPoruka = new javax.swing.JTextField();
        jButtonPosaljiIzabranom = new javax.swing.JButton();
        jTextFieldPoslednjaPoruka = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableSvePoruke = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                OdjaviKlijenta(evt);
            }
        });

        jButtonLogout.setText("Logout");
        jButtonLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLogoutActionPerformed(evt);
            }
        });

        jTableUseri.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTableUseri);

        jTextFieldPoruka.setText("Alooo");

        jButtonPosaljiIzabranom.setText("Posalji izabranom");
        jButtonPosaljiIzabranom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPosaljiIzabranomActionPerformed(evt);
            }
        });

        jLabel1.setText("Poslednja poruka:");

        jTableSvePoruke.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTableSvePoruke);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldPoruka)
                            .addComponent(jButtonPosaljiIzabranom, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE)
                            .addComponent(jButtonLogout)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(jLabel1)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldPoslednjaPoruka, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 383, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(27, 27, 27))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(90, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButtonLogout)
                                .addGap(52, 52, 52)
                                .addComponent(jTextFieldPoruka, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(46, 46, 46)
                                .addComponent(jButtonPosaljiIzabranom)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldPoslednjaPoruka, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(36, 36, 36))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void OdjaviKlijenta(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_OdjaviKlijenta
        KlijentskiZahtev kz=new KlijentskiZahtev(operacije.Operacije.logout, (User)trenutni);
        komunikacija.Komunikacija.getInstance().posaljiZahtev(kz);
    }//GEN-LAST:event_OdjaviKlijenta

    private void jButtonLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLogoutActionPerformed
         KlijentskiZahtev kz=new KlijentskiZahtev(operacije.Operacije.logout, (User)trenutni);
         komunikacija.Komunikacija.getInstance().posaljiZahtev(kz);
         this.dispose();
    }//GEN-LAST:event_jButtonLogoutActionPerformed

    private void jButtonPosaljiIzabranomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPosaljiIzabranomActionPerformed
        int red=jTableUseri.getSelectedRow();
        if(red==-1){
            JOptionPane.showMessageDialog(this, "Greska, izaberi red!");
              return;      
        }
        ModelTabeleUseri model=(ModelTabeleUseri) jTableUseri.getModel();
        Poruka p=new Poruka(-1, trenutni, model.getLista().get(red), jTextFieldPoruka.getText(), new Date());
        KlijentskiZahtev kz=new KlijentskiZahtev(operacije.Operacije.posaljiIzabranom,(Poruka) p);
        komunikacija.Komunikacija.getInstance().posaljiZahtev(kz);
        if(komunikacija.Komunikacija.getInstance().primiOdgovor().getOdgovor().equals("Uspeh")){
            JOptionPane.showMessageDialog(this, "Uspeh");
        }else{
            JOptionPane.showMessageDialog(this, "Greska pri slanju");
        }
        
    }//GEN-LAST:event_jButtonPosaljiIzabranomActionPerformed

    public void osvezi(){
        KlijentskiZahtev kz=new KlijentskiZahtev(operacije.Operacije.vratiOnlineUsere, null);
        komunikacija.Komunikacija.getInstance().posaljiZahtev(kz);
        List<User>lista=(List<User>) komunikacija.Komunikacija.getInstance().primiOdgovor().getOdgovor();
        System.out.println(lista);
        ModelTabeleUseri model=new ModelTabeleUseri(lista);
       jTableUseri.setModel(model);
        if(!lista.contains(trenutni)){
            this.dispose();
        }
    }
    public void popuniTextField(){
        KlijentskiZahtev kz=new KlijentskiZahtev(operacije.Operacije.vratiPoslednjuPoruku,(User) trenutni);
        komunikacija.Komunikacija.getInstance().posaljiZahtev(kz);
        jTextFieldPoslednjaPoruka.setText((String) komunikacija.Komunikacija.getInstance().primiOdgovor().getOdgovor());
    }
    public void popuniTabelu(){
        KlijentskiZahtev kz=new KlijentskiZahtev(operacije.Operacije.vratiPoruke, (User)trenutni);
        komunikacija.Komunikacija.getInstance().posaljiZahtev(kz);
        List<Poruka>lista=(List<Poruka>) komunikacija.Komunikacija.getInstance().primiOdgovor().getOdgovor();
        if(lista.isEmpty()){
            return;
        }
        ModelTabelePoruka model=new ModelTabelePoruka(lista);
        jTableSvePoruke.setModel(model);
    }
    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonLogout;
    private javax.swing.JButton jButtonPosaljiIzabranom;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableSvePoruke;
    private javax.swing.JTable jTableUseri;
    private javax.swing.JTextField jTextFieldPoruka;
    private javax.swing.JTextField jTextFieldPoslednjaPoruka;
    // End of variables declaration//GEN-END:variables
}
